name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'mlc_config.json'

    - name: Create Issue From File
      if: ${{ failure() }}
      id: ciff
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: Remove dead links from repository
        content-filepath: ./.github/ISSUE_TEMPLATE/issue.md

    - name: Create or Update Project Card
      if: ${{ steps.ciff.outputs.outcome == 'success' }}
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-number: '1'
        column-name: 'To do'
        issue-number: ${{ steps.ciff.outputs.issue-number }}
    
