name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'mlc_config.json'
    
    - name: create issue card
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-name: 'PurpleBriar/helium'
        column-name: 'To do'
