name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Create Issue From File
      id: ciff
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: An example issue
        content-filepath: ./CHANGELOG.md

    - name: Create or Update Project Card
      uses: peter-evans/create-or-update-project-card@v1
      with:
        project-number: '1'
        column-name: 'To do'
        issue-number: ${{ steps.ciff.outputs.issue-number }}
    
