name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Create Issue From File
      id: ciff
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: An example issue
        content-filepath: ./CHANGELOG.md
    
